### ISSUE TITLE
Membership Dashboard UI

### ISSUE THREAD

**Issue by xprilion** [dsc-x/omg-badge#3]
Boostrap + jQuery UI for the app

**Comment by rajinderpalsingh2001** [comment]
Kindly assign this issue to me.

**Comment by Abhijay007** [comment]
@xprilion sir can you please explain what type of UI you want?

And sir, I have one more question can I make three separate files for the existing codebase means `style.css`, `app. js'`, and `index.html.` It will help in increasing code readability and understandability for the future contributors.

**Comment by Abhijay007** [comment]
> Boostrap + jQuery UI for the app

@xprilion sir can you please explain what type of UI you want?

And sir, I have one more question can I make three separate files for the existing codebase means style.css, app. js', and index.html. It will help in increasing code readability and understandability for future contributors.

**Comment by xprilion** [comment]
@Abhijay007  The UI details will be posted here by @sairish2001 after preparation of wireframes and discussion around them, meanwhile, please feel free to suggest your own ideas based on the project requirements mention in the repo readme!

**Comment by Abhijay007** [comment]
> @Abhijay007 The UI details will be posted here by @sairish2001 after preparation of wireframes and discussion around them, meanwhile, please feel free to suggest your own ideas based on the project requirements mention in the repo readme!

ok got it 😃

**Comment by rajinderpalsingh2001** [comment]
@Abhijay007 UI created with Bootstrap and CSS

**Comment by rajinderpalsingh2001** [comment]
New Feature Added
1. User can crop the image after selecting
@Abhijay007 and if any other feature you want to add or have in mind feel free to tell.

**Comment by Abhijay007** [comment]
> New Feature Added
> 
> 1. User can crop the image after selecting
>    @Abhijay007 and if any other feature you want to add or have in mind feel free to tell.

Yeah, I have a suggestion that if you are using bootstrap in this project then you can introduce dark-mode support as well because if we start implementing it from now itself then it will easy for us to make changes in the future also. We just need to add a toggle button at the top right corner and need to make some CSS and js changes according to the toggle button.

**Comment by rajinderpalsingh2001** [comment]
@Abhijay007 Thanks for your contribution, it's a great idea.

**Comment by Abhijay007** [comment]
@xprilion sir, can I get an idea that when you gonna update this project with the latest UI and wireframes because I think I can contribute to this project but if I made some changes right now, that may become a problem in the future.

**Comment by Abhijay007** [comment]
@xprilion sir, can I get an idea that when you gonna update this project with the latest UI and wireframes because I think I can contribute to this project, but if I made some changes right now, that may become a problem in the future.

**Comment by rajinderpalsingh2001** [comment]
[https://sairish2001.github.io/omgframestesting.github.io/](https://sairish2001.github.io/omgframestesting.github.io/)

Just have a look to the Updated UI **(This project is hosted just for test purpose only till now)**
_**Kindly Visit, Use, Test* and Drop your suggestions in the comments.**_

*this is a beta release, some functions may not work.

**Comment by rajinderpalsingh2001** [comment]
@Abhijay007 kindly refer to it
[https://github.com/dsc-x/omg-frames/pull/4](https://github.com/dsc-x/omg-frames/pull/4)

**Comment by Abhijay007** [comment]
> @Abhijay007 kindly refer to it
> #4

ok

**Comment by rajinderpalsingh2001** [comment]
Update:

• Available API's implemented [refer-to-it](https://github.com/dsc-x/omg-frames-api) for API's
• Added Option to Manually Enter Filename before download begins
• Gallery Page Created and API implemented
• Minor Bugs fixed in UI

**Comment by arnabsen1729** [comment]
Couple of issues with the latest release:

### 1. 

![image](https://user-images.githubusercontent.com/51032928/103174368-8d19df80-4887-11eb-833e-bddce039708e.png)
Remove the values of the login forms. 

### 2.

Wrong credentials in login leads to infinite loading. If the response from the server is not 200 or 201 make a pop-up or message displaying the necessary info. 

### 3. 
![image](https://user-images.githubusercontent.com/51032928/103174447-395bc600-4888-11eb-810f-be4ab264f5c3.png)
Instead of having Home and Gallery at the top, we can add a Gallery icon on the left side along with other options, the logo will serve the purpose of 'Home'.

### 4. 
![image](https://user-images.githubusercontent.com/51032928/103174514-c7d04780-4888-11eb-93dc-8b4173afe228.png)
There is a create account button in the login modal but it will be better to have another separate button in the navbar for Sign Up

### 5.
Favicon is missing.

**Comment by rajinderpalsingh2001** [comment]
@arnabsen1729 Thanks for your valuable feedback, I will fix it.
